FROM jomjol/raspberry-opencv-tensorflow-lite

RUN [ "cross-build-start" ]

EXPOSE 3000

ENV PYTHONUNBUFFERED=1
ENV TZ Europe/Berlin
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone

WORKDIR /app
COPY ./requirements_raspi.txt .
RUN pip3 install --no-cache-dir -r ./requirements_raspi.txt
COPY . ./

RUN [ "cross-build-end" ]

CMD ["python3", "./wasseruhr.py"]
