FROM jomjol/raspberry-opencv-tensorflow-lite

EXPOSE 3000

ENV PYTHONUNBUFFERED=1

RUN [ "cross-build-start" ]

WORKDIR /app
COPY ./requirements.txt .
RUN pip3 install --no-cache-dir -r requirements_raspi.txt
COPY . ./

RUN [ "cross-build-end" ]

CMD ["python3", "./wasseruhr.py"]
